logging:
  level:
    net.shyshkin: debug
    io.rsocket: debug
#    root: debug
spring:
  application:
    name: client-graphql-rsocket-movie-app
  graphql:
    schema:
      locations: classpath:graphql
    rsocket:
      mapping: graphql
  rsocket:
    server:
      port: 6565
  main:
    web-application-type: none

  # Consul configuration
  cloud:
    discovery:
      enabled: false

app.service:
  review.base-url: http://localhost:8081/review
  movie.base-url: http://localhost:8081/movie
  customer.base-url: http://localhost:8081/customer

app:
  server:
    rsocket:
      setup-route: movie-app-client
      loadbalancer:
        static-addresses-l-b:
          instances:
            - host: localhost
              port: 7000
            - port: 7001
            - port: 7002

---
spring:
  config:
    activate:
      on-profile: webflux_enabled
  graphql:
    path: /graphql
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
      path: /graphiql
  main:
    web-application-type: reactive

---
spring:
  config:
    activate:
      on-profile: service-discovery
  cloud:
    discovery:
      enabled: true
    consul:
      discovery:
        enabled: true
        register: false
app:
  server:
    rsocket:
      setup-route: movie-app-client
      loadbalancer:
        discovery-service-l-b:
          service-name: server-graphql-rsocket-movie-app
          rsocket-port-metadata-field: rsocketPort



