logging:
  level:
    net.shyshkin: debug

spring:
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/${spring.profiles.active}
    graphiql:
      enabled: true
      path: /graphiql
    websocket:
      path: /graphql
app.caller-id-header: caller-id
app.client-id-header: client-id