spring:
  application:
    name: server-graphql-rsocket-movie-app
  rsocket:
    server:
      transport: tcp
      port: 7000
  main:
    web-application-type: reactive

logging:
  level:
    net.shyshkin: debug

