### Hello - sometimes does not work (RSC is better)
FNF hello
Host: 127.0.0.1:7000
Content-Type: application/json

Nazar

### Ping to client
RSOCKET graphql
Host: 127.0.0.1:6565
Content-Type: application/json

{
  "query": "query{ping}"
}

### REST ping over RSocker
GET localhost:8080/rest/ping
X-Client-Id: {{clientId}}

### REST get movie summary over RSocker
GET localhost:8080/rest/movies/4
X-Client-Id: {{clientId}}

### REST get movie details over RSocker
GET localhost:8080/rest/movies/5?detailsType=FULL
X-Client-Id: {{clientId}}

### REST get movies by genre over RSocker
GET localhost:8080/rest/movies?genre=ADVENTURE
X-Client-Id: {{clientId}}

