version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION:1.15-alpine}
    volumes:
      - ./conf-lb:/etc/nginx/conf.d
    ports:
      - 6999:6999
    command: "nginx -c /etc/nginx/conf.d/nginx.conf"