logging:
  level:
    net.shyshkin: debug

spring:
  main:
    allow-bean-definition-overriding: true

  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/${spring.profiles.active}
    graphiql:
      enabled: true
      path: /graphiql
    websocket:
      path: /graphql
