logging:
  level:
    net.shyshkin: debug

spring:
  graphql:
    path: /graphql
    schema:
      locations: classpath:graphql/${spring.profiles.active}
    graphiql:
      enabled: true
      path: /graphiql
    websocket:
      path: /graphql

customer:
  service:
    url: http://localhost:8080/graphql
  events:
    subscription:
      url: ws://localhost:8080/graphql
#      url: http://localhost:8080/graphql #also work